# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yanke\Documents\Python\UI\NapTimer\Nap.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 292)
        MainWindow.setStyleSheet("QMainWindow > QWidget { background-color: rgb(59, 59, 59);}\n"
" \n"
"QPushButton:hover {\n"
"background-color: rgb(198, 198, 198);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"background-color: rgb(198, 198, 198);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.waveButton = QtWidgets.QPushButton(self.centralwidget)
        self.waveButton.setGeometry(QtCore.QRect(30, 160, 41, 41))
        self.waveButton.setStyleSheet("border-image: url(:/ui/Pictures/UI Icons/big-wave.svg);")
        self.waveButton.setText("")
        self.waveButton.setCheckable(True)
        self.waveButton.setChecked(False)
        self.waveButton.setObjectName("waveButton")
        self.fireplaceButton = QtWidgets.QPushButton(self.centralwidget)
        self.fireplaceButton.setGeometry(QtCore.QRect(100, 160, 40, 40))
        self.fireplaceButton.setToolTip("")
        self.fireplaceButton.setStyleSheet("border-image: url(:/ui/Pictures/UI Icons/fireplace.svg);")
        self.fireplaceButton.setText("")
        self.fireplaceButton.setCheckable(True)
        self.fireplaceButton.setObjectName("fireplaceButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.timeBox = QtWidgets.QSpinBox(self.centralwidget)
        self.timeBox.setGeometry(QtCore.QRect(180, 260, 42, 22))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        self.timeBox.setFont(font)
        self.timeBox.setStyleSheet("")
        self.timeBox.setMaximum(60)
        self.timeBox.setObjectName("timeBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 220, 181, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.aboutButton = QtWidgets.QPushButton(self.centralwidget)
        self.aboutButton.setGeometry(QtCore.QRect(370, 260, 25, 25))
        self.aboutButton.setStyleSheet("border-image: url(:/ui/Pictures/UI Icons/info-filled.svg);")
        self.aboutButton.setText("")
        self.aboutButton.setObjectName("aboutButton")
        self.frogButton = QtWidgets.QPushButton(self.centralwidget)
        self.frogButton.setGeometry(QtCore.QRect(170, 160, 40, 40))
        self.frogButton.setStyleSheet("border-image: url(:/ui/Pictures/UI Icons/frog.svg);")
        self.frogButton.setText("")
        self.frogButton.setCheckable(True)
        self.frogButton.setObjectName("frogButton")
        self.rainButton = QtWidgets.QPushButton(self.centralwidget)
        self.rainButton.setGeometry(QtCore.QRect(250, 160, 40, 40))
        self.rainButton.setStyleSheet("border-image: url(:/ui/Pictures/UI Icons/cloud.svg);")
        self.rainButton.setText("")
        self.rainButton.setCheckable(True)
        self.rainButton.setObjectName("rainButton")
        self.noiseButton = QtWidgets.QPushButton(self.centralwidget)
        self.noiseButton.setGeometry(QtCore.QRect(330, 160, 40, 40))
        self.noiseButton.setStyleSheet("border-image: url(:/ui/Pictures/UI Icons/headphones.svg);")
        self.noiseButton.setText("")
        self.noiseButton.setCheckable(True)
        self.noiseButton.setObjectName("noiseButton")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(370, 10, 24, 24))
        self.closeButton.setStyleSheet("border-image: url(:/ui/Pictures/UI Icons/close.svg);")
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.minButton = QtWidgets.QPushButton(self.centralwidget)
        self.minButton.setGeometry(QtCore.QRect(350, 10, 24, 24))
        self.minButton.setStyleSheet("border-image: url(:/ui/Pictures/UI Icons/twotone-minimize.svg);")
        self.minButton.setText("")
        self.minButton.setObjectName("minButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 351, 61))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.timeBox.valueChanged['int'].connect(MainWindow.set_time) # type: ignore
        self.waveButton.pressed.connect(lambda: MainWindow.start_playing(1)) # type: ignore
        self.waveButton.pressed.connect(MainWindow.button_control) # type: ignore
        self.fireplaceButton.pressed.connect(MainWindow.button_control) # type: ignore
        self.frogButton.pressed.connect(MainWindow.button_control) # type: ignore
        self.rainButton.pressed.connect(MainWindow.button_control) # type: ignore
        self.noiseButton.pressed.connect(MainWindow.button_control) # type: ignore
        self.fireplaceButton.pressed.connect(lambda: MainWindow.start_playing(2)) # type: ignore
        self.frogButton.pressed.connect(lambda: MainWindow.start_playing(3)) # type: ignore
        self.rainButton.pressed.connect(lambda: MainWindow.start_playing(4)) # type: ignore
        self.noiseButton.pressed.connect(lambda: MainWindow.start_playing(5)) # type: ignore
        self.minButton.pressed.connect(MainWindow.showMinimized) # type: ignore
        self.closeButton.pressed.connect(MainWindow.close_window) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.waveButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Tooltip on button with image</p></body></html>"))
        self.fireplaceButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Fireplace</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Audio Select"))
        self.label_2.setText(_translate("MainWindow", "Select your nap length in minutes"))
        self.minButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Pick the length of your nap, then click on the sound you would like to fall asleep to"))
import UI_rc
